apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: cm9vdA==         # Base64 encoded value for "root"
  mongo-password: cm9vdA==     # Base64 encoded value for "root"
