apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo  # Ensure this matches your MongoDB deployment's labels
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
